# This file was generated by GoReleaser. DO NOT EDIT.
cask "sumup" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "f884003e59bb57699cecca4fb8d36653f189ced8ae6f67525e9691d3801936a9"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1f437f7ef7a92e9861a9474f7c770e7d85f192fc4192360cdedac9ab1ae52352"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "31360dda1d38041080b9adcd35cb7e1f970429c3b74902b5eca59b1de276621a"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "51fd76f7bd23f8843a529fa9789cda91337eb25d238373ab054ccda47a87685a"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sumup"
  desc "Command line tool for interacting with SumUp APIs."
  homepage "https://developer.sumup.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sumup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sumup"]
    end
  end

  # No zap stanza required

end
