# This file was generated by GoReleaser. DO NOT EDIT.
cask "sumup" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "9d8ee11c34946762bed7b9bf0f1918deb213c6616ae7818e6dff96eac9c21b88"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2f5ed1dbd4721d50e02f165074e1893bd9f8b2993c4afddf8c43aba34d2d81aa"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "30d8d9e5ee61732000ee8a83037b123b0d8ae4e606fb763c7f88e760b28af05a"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "00598bfb0c1423f75b3e399fc5456a68837a67e572302e5d4307ae7166f0159b"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sumup"
  desc "Command line tool for interacting with SumUp APIs."
  homepage "https://developer.sumup.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sumup"
  manpage "man/man1/sumup.1.gz"
  bash_completion "completions/sumup.bash"
  fish_completion "completions/sumup.fish"
  zsh_completion "completions/sumup.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sumup"]
    end
  end

  # No zap stanza required

end
