# This file was generated by GoReleaser. DO NOT EDIT.
cask "sumup" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "8d15ff2062c0e7f54305e855a6924177d8b8a1ca1570e55bbf4402fe791ea312"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a426b7319a0429912a94ae761b99ae60f490b795ecd10c6135277fe290dcd7a7"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "031a437fc93216080e011ab2d1d8d315e5ef747329a3bc7f54b69c337167d3d8"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6b30c0c6092f95c4127156cbf8bd7a9dc7a6585811f9975624e530a89c7309f8"
      url "https://github.com/sumup/sumup-cli/releases/download/v#{version}/sumup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sumup"
  desc "Command line tool for interacting with SumUp APIs."
  homepage "https://developer.sumup.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sumup"
  manpage "man/man1/sumup.1.gz"
  bash_completion "completions/sumup.bash"
  fish_completion "completions/sumup.fish"
  zsh_completion "completions/sumup.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sumup"]
    end
  end

  # No zap stanza required

end
