# frozen_string_literal: true

cask_path = "Casks/sumup.rb"
abort("#{cask_path} is missing") unless File.exist?(cask_path)

cask = File.read(cask_path)
checks = {
  "generated header" => cask.start_with?("# This file was generated by GoReleaser. DO NOT EDIT.\n"),
  "sumup cask token" => cask.match?(/^cask "sumup" do$/),
  "semantic version" => cask.match?(/^  version "\d+\.\d+\.\d+"$/),
  "homepage" => cask.include?('  homepage "https://developer.sumup.com"'),
  "binary" => cask.include?('  binary "sumup"'),
  "manpage" => cask.include?('  manpage "man/man1/sumup.1.gz"'),
  "bash completion" => cask.include?('  bash_completion "completions/sumup.bash"'),
  "zsh completion" => cask.include?('  zsh_completion "completions/sumup.zsh"'),
  "fish completion" => cask.include?('  fish_completion "completions/sumup.fish"'),
  "macos amd64 archive" => cask.match?(/sumup_#\{version\}_macOS_x86_64\.tar\.gz/),
  "macos arm64 archive" => cask.match?(/sumup_#\{version\}_macOS_arm64\.tar\.gz/),
  "linux amd64 archive" => cask.match?(/sumup_#\{version\}_linux_x86_64\.tar\.gz/),
  "linux arm64 archive" => cask.match?(/sumup_#\{version\}_linux_arm64\.tar\.gz/),
  "release host" => cask.scan(%r{https://github\.com/sumup/sumup-cli/releases/download/v#\{version\}/}).length == 4,
  "sha256 count" => cask.scan(/^\s+sha256 "[a-f0-9]{64}"$/).length == 4,
  # Re-add after md/signing: "no quarantine bypass" => !cask.include?("com.apple.quarantine"),
}

failed = checks.reject { |_description, passed| passed }.keys
abort("#{cask_path} validation failed: #{failed.join(', ')}") unless failed.empty?

puts "#{cask_path} OK"
